=== Lluisaac/EtudiantSimulator/EtudiantSimulator/listes/events.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT ListEvents (Event*)>
<!ELEMENT Event (joursRestantsProbaAjoutee?,default?,choix*)>
<!ELEMENT default (modifEvent?, modifObjet?, modifPlayer?)>
<!ELEMENT choix (modifEvent?, modifObjet?, modifPlayer?)>
<!ELEMENT modifEvent (eventM+)>
<!ELEMENT modifObjet (Objet+)>
<!ELEMENT Objet (upgrade|bonus)>
<!ELEMENT Objet (modifEvent?, modifObjet?)>
<!ELEMENT eventM (default?,choix*)>

<!ELEMENT joursRestantsProbaAjoutee EMPTY>
<!ELEMENT modifPlayer EMPTY>
<!ELEMENT upgrade EMPTY>
<!ELEMENT bonus EMPTY>

<!ATTLIST Event nom CDATA #REQUIRED>
<!ATTLIST Event description CDATA #REQUIRED>


<!ATTLIST Event archetype CDATA  "Icone">
<!ATTLIST Event date CDATA #IMPLIED>
<!ATTLIST Event occurence CDATA  "0">
<!ATTLIST Event probabilite CDATA  "0">

<!ATTLIST joursRestantsProbaAjoutee jRestants CDATA #REQUIRED>
<!ATTLIST joursRestantsProbaAjoutee probaAjoutee CDATA #REQUIRED>

<!ATTLIST eventM nom CDATA #REQUIRED>
<!ATTLIST eventM date CDATA #IMPLIED>
<!ATTLIST eventM occurence CDATA  "0">
<!ATTLIST eventM probabilite CDATA  "0">

<!ATTLIST Objet nom CDATA #REQUIRED>
<!ATTLIST Objet dispo CDATA #REQUIRED>

<!ATTLIST upgrade cout CDATA "0">
<!ATTLIST upgrade argentJ CDATA "0">
<!ATTLIST upgrade savoirJ CDATA "0">
<!ATTLIST upgrade faimJ CDATA "0">
<!ATTLIST upgrade fatigueJ CDATA "0">
<!ATTLIST upgrade bonheurJ CDATA "0">
<!ATTLIST upgrade tempsLibreJ CDATA "0">
<!ATTLIST upgrade durabilite CDATA "0">

<!ATTLIST bonus cout CDATA "0">
<!ATTLIST bonus savoir CDATA "0">
<!ATTLIST bonus faim CDATA "0">
<!ATTLIST bonus fatigue CDATA "0">
<!ATTLIST bonus bonheur CDATA "0">
<!ATTLIST bonus tempsLibre CDATA "0">
<!ATTLIST bonus durabilite CDATA "0">

<!ATTLIST modifPlayer argent CDATA #IMPLIED>
<!ATTLIST modifPlayer savoir CDATA #IMPLIED>
<!ATTLIST modifPlayer faim CDATA #IMPLIED>
<!ATTLIST modifPlayer fatigue CDATA #IMPLIED>
<!ATTLIST modifPlayer bonheur CDATA #IMPLIED>
<!ATTLIST modifPlayer argentJ CDATA #IMPLIED>
<!ATTLIST modifPlayer savoirJ CDATA #IMPLIED>
<!ATTLIST modifPlayer faimJ CDATA #IMPLIED>
<!ATTLIST modifPlayer fatigueJ CDATA #IMPLIED>
<!ATTLIST modifPlayer bonheurJ CDATA #IMPLIED>
<!ATTLIST modifPlayer gainParMois CDATA #IMPLIED>
<!ATTLIST modifPlayer loyer CDATA #IMPLIED>
<!ATTLIST modifPlayer tempsLibre CDATA #IMPLIED>
<!ATTLIST modifPlayer tempsLibreJ CDATA #IMPLIED>

<!ATTLIST choix nom CDATA #REQUIRED>
<!ATTLIST choix noDefault CDATA "false">

=== Lluisaac/EtudiantSimulator/EtudiantSimulator/listes/temp.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE ListEvents SYSTEM "events.dtd"><ListEvents><Event nom="Casse" description="ggggggggggggggggggggggggggggggggg" archetype="Mort" occurence="-1" probabilite="15"><default><modifPlayer argent="50"/></default><choix nom="oki"></choix><choix nom="yay"></choix></Event><Event nom="Machin" description="cest un test" archetype="Passion" occurence="-1" probabilite="5"><default><modifEvent><eventM nom="Casse" probabilite="-5"/></modifEvent></default></Event><Event nom="Truc" description="test daté" archetype="Mort"		occurence="-1" date="3/6/1"><default><modifEvent><eventM nom="Machin"><default><modifEvent><eventM nom="Casse" probabilite="5" /></modifEvent></default></eventM></modifEvent></default></Event><Event nom="Sortir" description="Voulez-vous sortir dehors?"		archetype="Amis" occurence="-1" probabilite="8"><default></default><choix nom="oui"></choix><choix nom="non"></choix></Event><Event nom="Vous êtes en couple"		description="Bien joué ! Tu as enfin trouvé ta moitié !"		archetype="Copine" occurence="1" probabilite="0"><default><modifPlayer argentJ="-10" bonheurJ="2"></modifPlayer></default></Event><Event nom="Coup de foudre"		description="Dès le premier regard, elle a été conquise par votre charme !"		archetype="Passion" occurence="1" probabilite="1"></Event><Event nom="Cible repérée"		description="Vous avez trouvé l'objectif de votre dur labeur."		archetype="Copine" occurence="1" probabilite="0"></Event><Event nom="Sortir avec"		description="Vous décidez d'aller partager un moment avec votre future conquête."		archetype="Copine" occurence="-1" probabilite="0"></Event></ListEvents>

=== Lluisaac/EtudiantSimulator/EtudiantSimulator/listes/events.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ListEvents SYSTEM "events.dtd">
<ListEvents>
	<Event nom="" description="" archetype="" date="" occurence="" probabilite="">
		<joursRestantsProbaAjoutee jRestants="" probaAjoutee="" />
		<default>
			<modifEvent>
				<eventM nom="" date="" occurence="" probabilite=""/>
			</modifEvent>
			<modifObjet>
				<objet nom="" dispo="">
					<upgrade argentJ="" savoirJ="" faimJ="" fatigueJ="" bonheurJ="" tempsLibreJ=""  cout="" durabilite=""/>
				</objet>
			</modifObjet>
			<modifPlayer argent="" savoir="" faim="" fatigue="" bonheur="" argentJ="" savoirJ="" faimJ="" fatigueJ="" bonheurJ="" gainParMois="" loyer="" tempsLibre="" tempsLibreJ=""/>
		</default>
		<choix nom="" noDefault="">
			<modifEvent>
				<eventM nom="" date="" occurence="" probabilite=""/>
			</modifEvent>
			<modifObjet>
				<objet nom="" dispo="" >
					<bonus savoir="" faim="" fatigue="" bonheur="" tempsLibre="" cout="" durabilite=""/>
				</objet>
			</modifObjet>
			<modifPlayer argent="" savoir="" faim="" fatigue="" bonheur="" argentJ="" savoirJ="" faimJ="" fatigueJ="" bonheurJ="" gainParMois="" loyer="" tempsLibre="" tempsLibreJ=""/>
		</choix>
		<choix nom="" noDefault="">
			<modifPlayer argent="" savoir="" faim="" fatigue="" bonheur="" argentJ="" savoirJ="" faimJ="" fatigueJ="" bonheurJ="" gainParMois="" loyer="" tempsLibre="" tempsLibreJ=""/>
		</choix>
	</Event>
</ListEvents>
